# Generated by Django 4.2.5 on 2024-02-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DcsCatServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Что входит в услугу?'), ('2', 'Как это вам поможет?')], max_length=1, verbose_name='Категория')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование')),
                ('dsc', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(verbose_name='Активный?')),
            ],
            options={
                'verbose_name': 'Что входит в услугу?',
                'verbose_name_plural': 'Что входит в услуги?',
            },
        ),
        migrations.CreateModel(
            name='Dignities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('dsc', models.TextField(verbose_name='Описание')),
                ('is_active', models.TextField(verbose_name='Активный?')),
            ],
            options={
                'verbose_name': 'За что нас ценят?',
                'verbose_name_plural': 'За что нас ценят?',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата обращения')),
                ('username', models.CharField(max_length=155, verbose_name='Имя пользователя')),
                ('number_phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('name_company', models.CharField(max_length=55, verbose_name='Компания')),
                ('document', models.FileField(upload_to='feedback/document/%Y/%m/%d/', verbose_name='Техническое задание')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('is_successfully', models.BooleanField(default=False, verbose_name='Успешно')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Разработчик'), ('2', 'Клиент')], max_length=1, verbose_name='От кого?')),
                ('username', models.CharField(max_length=50, verbose_name='Имя Фамилия')),
                ('post', models.CharField(max_length=20, verbose_name='Должность')),
                ('quotes', models.TextField(verbose_name='Цитата')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('1', 'Разработка систем с веб-интерфейсом'), ('2', 'Разработка дизайна'), ('3', 'Обслуживание IT-инфраструктуры'), ('4', 'Разработка мобильных приложений'), ('5', 'Разработка умных систем'), ('6', 'Интернет реклама')], max_length=1, verbose_name='Категория')),
                ('dsc', models.TextField(verbose_name='Описание')),
                ('included_in_the_service', models.ManyToManyField(to='server.dcscatservices', verbose_name='Подробное описание')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование')),
                ('bw_preview_photo', models.ImageField(upload_to='photo/project/bw_preview/%Y/%m/%d/', verbose_name='Фотография превью')),
                ('c_preview_photo', models.ImageField(upload_to='photo/project/c_preview/%Y/%m/%d/', verbose_name='Фотография превью')),
                ('title_photo', models.ImageField(upload_to='photo/project/title/%Y/%m/%d/', verbose_name='Фотография заголовка')),
                ('dsc_project', models.TextField(verbose_name='О проекте')),
                ('dsc_task', models.TextField(verbose_name='Задача')),
                ('photo_task', models.ImageField(upload_to='photo/project/task/%Y/%m/%d/', verbose_name='Фотография задачи')),
                ('dsc_realization', models.TextField(verbose_name='Реализация')),
                ('photo_realization', models.ImageField(upload_to='photo/project/realization/%Y/%m/%d/', verbose_name='Фотография реализации')),
                ('category_services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.services', verbose_name='Категория услуги')),
                ('quotes', models.ManyToManyField(to='server.quotes', verbose_name='Цитаты')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
