# Generated by Django 4.2.5 on 2024-02-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Категория услуги'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='bw_preview_photo',
            field=models.ImageField(upload_to='photo/project/bw_preview/%Y/%m/%d/', verbose_name='Фотография превью чб'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='c_preview_photo',
            field=models.ImageField(upload_to='photo/project/c_preview/%Y/%m/%d/', verbose_name='Фотография превью цветная'),
        ),
    ]
