# Generated by Django 4.2.5 on 2024-02-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_feedback_category_alter_projects_bw_preview_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dignities',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активный?'),
        ),
    ]
