# Generated by Django 4.2.5 on 2024-02-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_projects_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='feedback/document/%Y/%m/%d/', verbose_name='Техническое задание'),
        ),
    ]
