# Generated by Django 4.2.5 on 2024-02-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_feedback_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_display_main_page',
            field=models.BooleanField(default=False, verbose_name='Отображать на гл стр?'),
        ),
    ]
